version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo install phase
  pre_build:
    commands:
      - echo pre_build phase
      - echo `java -version`
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/pk-demo-codepipeline-0.0.1-SNAPSHOT.jar